[package]
name = "projecteuler-solutions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

itertools = "0.10.5"
num-bigint = "0.4"
primal = "0.3.0"
prime_factorization = "1.0.1"
time = "0.3.19"
